os: Visual Studio 2015

environment:
  matrix:
    - platform: Win32
      configuration: Debug
    - platform: Win32
      configuration: Release
    - platform: x64
      configuration: Debug
    - platform: x64
      configuration: Release

matrix:
  fast_finish: false

build:
  parallel: true
  project: Argon2.sln
  verbosity: minimal

test_script:
  - ps: dir
  - ps: Argon2OptTestCI.exe
  - ps: Argon2RefTestCI.exe
